### ISSUE TITLE
Launch Survey from a URL

### ISSUE THREAD

**Issue by ianfieldhouse** [edina/crowdsurvey#26]
Given a launch URL containing survey id, the app should:
- [x] activate on request of correctly formed URL [#27]
- [ ] check if the requested survey is already cached on the device [#28], and if not
- [x] check that the requested survey exists on the remote server [#29]
- [ ] download the requested survey resources [#30]
- [x] make the survey the active survey [#31]

**Comment by benismobile** [comment]
putting native CrowdSurvey apps on hold for the moment, pending project review
